config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :unpublished, on: :collection
    resources :comments, shallow: true
    resources :subscriptions,
              only: [:create, :destroy], shallow: true
  end
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users
  end

  # get 'welcome/index'

  root 'welcome#index'
  # root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_many :subscriptions
  has_many :subscribers, source: :user, through: :subscriptions
  #has_and_belongs_to_many :categories
  has_many :categories_posts
  has_many :categories, through: :categories_posts
  validates :title, :body, presence: true

  scope :reverse_order, -> (order){ order(created_at: :desc) }
  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }

  after_create :subscribed_author




  public
 def categories_titles
  #categories.map(&:title).join ', '
  categories.pluck(:title).join ', '
 end

  protected

  def subscribed_author
    user.subscribe_to(self)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :publish, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]


  # GET /posts
  def index
    @posts = Post.reverse_order(:desc).published.all
  end

  def unpublished
    @posts = Post.reverse_order(:desc).unpublished.all
    render :index
  end
  # GET /posts/1n
  def publish
    @post.published = true
    if post.save
      redirect_to unpublished_posts_path
    else
      render :edit
    end

    def unpublish
      @post.published = false
      if @post.save
        redirect_to unpublished_posts_path
      else
        render :edit
      end
    end
  end

  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end
  #Проверка пользователя на авторство
  def check_owner
    unless
      current_user.author_of?(@post) || current_user.admin?
      redirect_to posts_path, alert: 'У Вас нет прав на данное действие'
    end
  end
  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Пост успешно создан.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Пост отредактирован.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Пост удален.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :published, category_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
   <%= render 'common/errors', object: @post %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

    <div class="field">
      <%= f.label :published, 'Опубликовать' %><br>
      <%= f.check_box :published %>


    <div class="field">
      <%= f.label :category_ids, "Категории" %><br>
      <%= f.collection_select :category_ids, Category.all, :id, :title, {}, { multiple: true} %>

    </div>


    <div class="actions">
    <%= f.submit t('.submit', action: @post.new_record? ? t('common.create') : t('common.update') )%>
  </div>
<% end %>

app/views/posts/_post.html.erb
    <table class="table  table-striped table-bordered">
      <tbody>
     <h4><strong>
      <%= link_to post.title, post %>
     </strong></h4><br>
       <I><%= post.categories_titles %></I>

    <p>
    <%= truncate(post.body, length: 200) %><br>
    <%= link_to 'Читать далее... ', post %></p>


  <p><%= link_to t('common.show'), post %></p>
     <% if user_signed_in? %>
          <% if current_user.author_of?(post) %>
            <p><%= link_with_icon :pencil, edit_post_path(post), title: t('common.edit') %>
            </p>

            <p><%= link_with_icon 'trash-o', post, title: t('common.delete'), method: :delete, data: { confirm: 'Вы уверены?' } %></p>
          <% end %>
            <td> <% if current_user.subscribed_to?(post) %>
            <%= link_to 'Отписаться', current_user.subscription_for(post), method: :delete, notice: "Отписан"%>
                <% else %>
            <%= link_to 'Подписаться', post_subscriptions_path(post), method: :post, notice: 'Подписка' %>
                <% end %>
      </td>

          <% end %>
    </tbody>

    </table>

app/views/posts/edit.html.erb
<h1>Редактировать пост</h1>

<%= render 'form' %>

<%= link_to t('common.show'), @post %> |
<%= link_to t('common.back'), posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список постов</h1>

<td><strong><%= link_to t('.new_post'), new_post_path %></strong></td>
<%= link_to "Черновики", unpublished_posts_path %>

<table>


  <tbody><p>

  <%= render @posts %></p>


  </tbody>
</table>

<br>


<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to t('common.back'), posts_path %>

app/views/posts/show.html.erb
<p>

  <h1><%= @post.title %></h1>
</p>
<p><strong> Категории:</strong>

<%= @post.categories_titles %>


</p>
<% if @post.user.present? %>
<p><strong> Автор:</strong>

  <%= @post.user.email %>


</p>
    <% end %>
<p>

  <%= @post.body %>
</p>
<% if @post.comments.empty? %>
    <h4>комментариев пока нет</h4>

    <% else %>
    <h3> Комментарии </h3>
    <% @post.comments.each do |comment| %>
        <p><%= comment.body %></p>
        <p><%= link_with_icon 'trash-o' , comment, title: t('common.delete'), method: :delete %></p>
        <% end %>
<% end %>
    <h4>Новый комментарий</h4>
    <%= render 'comments/form' %>



<%= link_to t('common.back'), posts_path %>