config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :unpublished, on: :collection
    resources :comments, shallow: true
    resources :subscriptions,
              only: [:create, :destroy], shallow: true
  end
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users
  end

  # get 'welcome/index'

  root 'welcome#index'
  # root 'posts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  #has_and_belongs_to_many :posts
  has_many :categories_posts
  has_many :posts, through: :categories_posts
  validates :title, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]


      # GET /categories
    def index
      @categories = Category.all
    end

    # GET /categories/1
    def show
      @category = Category.find(params[:id])
      @posts = @category.posts
    end


    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'Категория создана.' }

        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /categories/1
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to edit_admin_category_path, notice: 'Категория отредактирована.' }
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Категория удалена.' }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
  end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end


  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Категория создана.' }

      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Категория отредактирована.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Категория удалена.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title)
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
    <%= render 'common/errors', object: @category %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_area :title %>
    </div>
    <div class="actions">
      <%= f.submit t('.submit')%>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Редактировать категории</h1>

<%= render 'form' %>

<%= link_to 'Показать', @category %> |
<%= link_to 'Назад', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Категории</h1>

<table>
  <thead>
  <tr>
    <th>Заголовок</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Показать', [:admin, category] %></td>
        <td><%= link_to 'Редактировать', edit_category_path(category) %></td>
        <td><%= link_to 'Удалить', [:admin, category], method: :delete, data: { confirm: 'Уверены?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новая категория', new_category_path %>
<%= link_to 'На главную', root_path %>

app/views/categories/new.html.erb
<h1>Новая категория</h1>

<%= render 'form' %>

<%= link_to 'Назад', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %></p>
<% if @category.posts.empty? %>
    <h4>Категория пустая</h4>
    <% else %>
<%= render @posts %>
    <% end %>
<%= link_to 'Редактировать', edit_admin_category_path(@category) %> |
<%= link_to 'Назад', admin_categories_path %>
<% if current_user && current_user.admin? %>
<%= link_to 'Все категории', admin_categories_path %>
<% end %>