config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :unpublished, on: :collection
    resources :comments, shallow: true
    resources :subscriptions,
              only: [:create, :destroy], shallow: true
  end
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users
  end

  # get 'welcome/index'

  root 'welcome#index'
  # root 'posts#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :profile
  has_many :posts
  has_many :comments

  has_many :subscriptions
  has_many :subscribed_posts, source: :post, through: :subscriptions

  def author_of?(object)
    id == object.user_id
  end

  def subscribed_to?(post)
    !!subscription_for(post)
  end

  def subscription_for(post)
   @subscription ||= subscriptions.where(post: post).first
  end

  def subscribe_to(post)
    subscribed_posts << post
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:destroy]

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'Пользователь удален'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:id)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <div class="field">
      <%= f.label :email, 'E-mail' %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :admin, 'Admin' %><br>
      <%= f.check_box :admin %>
    </div>
    <div class="actions">
      <%= f.submit%>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Редактировать пользователя</h1>

<%= render 'form' %>

<%= link_to t('common.show'), @user %> |
<%= link_to t('common.back'), admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Пользователи</h1>

<table>
  <thead>
  <tr>
    <th>Читайте</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>

        <td><%= link_with_icon :pencil, edit_admin_user_path(user), title: t('common.edit') %></td>
        <td><%= link_with_icon 'trash-o', [ :admin, user], title: t('common.delete'),  method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый пользователь', new_admin_user_path %>
<%= link_to 'На главную', root_path %>

app/views/admin/users/new.html.erb
<h1>Новый пользователь</h1>

<%= render 'form' %>

<%= link_to t('common.back'), admin_users_path %>

app/views/admin/users/show.html.erb
<strong>Title:</strong>
<%= @user.email %>
</p>
<%= render @users %>
<%= link_to t('common.edit'), edit_admin_user_path(@user) %> |
<%= link_to t('common.back'), admin_categories_path %>
<% if current_user && current_user.admin? %>
    <%= link_to 'Все категории', admin_categories_path %>
<% end %>